name: Summarize

permissions: {}

on:
  workflow_call:
    inputs:
      date:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      models: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: koki-develop/summarize-repository-activities@5d52dbfec51c4376d716f0de26099002b6a5aa37 # v0.0.7
        id: summarize
        with:
          locale: ja
          github-token: ${{ github.token }}
          days-ago: 1
          ai-model: openai/gpt-4o-mini
          ai-api-key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ inputs.repository }}
          releases-limit: 20
          pull-requests-limit: 20
          issues-limit: 20

      - name: Save summary
        env:
          REPOSITORY: ${{ inputs.repository }}
          SUMMARY: ${{ steps.summarize.outputs.summary }}
          DATE: ${{ inputs.date }}
        run: |
          mkdir -p "${REPOSITORY}"
          {
            echo "# [${REPOSITORY}](https://github.com/${REPOSITORY})"
            echo ""
            echo "${SUMMARY}"
          } > "${REPOSITORY}/${DATE}.md"

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit summary
        env:
          REPOSITORY: ${{ inputs.repository }}
          DATE: ${{ inputs.date }}
        run: |
          git add "${REPOSITORY}/${DATE}.md"
          git commit -m "Update summary for ${REPOSITORY} on ${DATE}"

      - name: Push changes
        run: |
          git fetch origin main
          git rebase origin/main
          git push origin main
