name: Summarize

permissions: {}

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    outputs:
      summary:
        value: ${{ jobs.summarize.outputs.summary }}

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      models: read
    outputs:
      summary: ${{ steps.summarize.outputs.summary }}
    steps:
      - uses: koki-develop/summarize-repository-activities@v0
        id: summarize
        with:
          github-token: ${{ github.token }}
          days-ago: 7
          ai-model: openai/gpt-4o-mini
          repository: ${{ inputs.repository }}
          releases-limit: 1
          pull-requests-limit: 1
          issues-limit: 1
