name: Weekly

permissions: {}

on:
  workflow_dispatch:

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Get date
        id: get-date
        run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"

  list-repositories:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.list.outputs.json }}
    steps:
      - name: List repositories
        id: list
        env:
          REPOSITORIES: |
            - hashicorp/terraform
            - hashicorp/terraform-provider-aws
        run: |
          {
            echo "json<<EOF"
            echo "${REPOSITORIES}" | yq --output-format json
            echo EOF
          } >> "${GITHUB_OUTPUT}"

  summarize:
    needs:
      - get-date
      - list-repositories
    uses: ./.github/workflows/_summarize.yml
    strategy:
      max-parallel: 1
      matrix:
        repository: ${{ fromJson(needs.list-repositories.outputs.json) }}
    permissions:
      contents: write
      models: read
    with:
      date: ${{ needs.get-date.outputs.date }}
      repository: ${{ matrix.repository }}
